
title: "Flutter Developer in Melbourne, Australia"
description: >- 
  Director of <a href="https://www.nimblesite.co/" style="color:white;text-decoration: underline;">Nimblesite</a>, Melbourne's Premiere Flutter Development Agency. He has been developing software for over 20 years. Passionate Mobile Apps and developers, Nimblesite can help you hire the right developer for your project. Call today <a href="tel:1300794205" style="color:white;text-decoration: underline;">1300 794 205</a>

phone_number: "1300 794 205"

twitter:
  username: cfdevelop
  card: summary

address_01: 'Melbourne, Australia'
copyright_text: "© 2024 Christian Findlay. All rights reserved."

#For jekyll-seo-tag
social:
  name: Christian Findlay
  links:
    - https://twitter.com/cfdevelop
    - https://www.facebook.com/cfdevelop
    - https://www.linkedin.com/in/christian-findlay/
    - https://github.com/MelbourneDeveloper
    - https://www.youtube.com/channel/UCBEdRhnuksiUnLonJT9lIaw

social_accounts:
  title: "Follow Me"
  links:

    - url: "https://www.linkedin.com/in/christian-findlay/"
      icon: "jam jam-linkedin"

    - url: "https://twitter.com/CFDevelop"
      icon: "jam jam-twitter"

    - url: "https://www.facebook.com/cfdevelop/"
      icon: "jam jam-facebook"

    - url: "https://www.youtube.com/channel/UCBEdRhnuksiUnLonJT9lIaw"
      icon: "jam jam-youtube"

external_links:
  title: "More"
  links:
    - text: "Home"
      url: "/#home"
    - text: "Services"
      url: "/#services"
    - text: "About"
      url: "/#about"
    - text: "Portfolio"
      url: "/#portfolio"
    - text: "Testimonials"
      url: "/#testimonials"
    - text: "FAQ"
      url: "/#faq"
    - text: "Contact"
      url: "/#contact"
    - text: "Blog"
      url: "/blog"

one_page_nav_settings:
  links:
    - text: "Home"
      url: "/#home"
    - text: "Services"
      url: "/#services"
    - text: "About"
      url: "/#about"
    - text: "Portfolio"
      url: "/#portfolio"
    - text: "Testimonials"
      url: "/#testimonials"
    - text: "FAQ"
      url: "/#faq"
    - text: "Contact"
      url: "/#contact"
    - text: "Blog"
      url: "/blog"

author_page_header:
  header_background_image: "assets/images/art/bg31.jpg"

gallery:
  images:
    - img: "assets/images/art/z1.svg"
    - img: "assets/images/art/z2.svg"
    - img: "assets/images/art/z3.svg"
    - img: "assets/images/art/z4.svg"
    - img: "assets/images/art/z5.svg"
    - img: "assets/images/art/z6.svg"
    - img: "assets/images/art/z7.svg"
    - img: "assets/images/art/z8.svg"
